$env:PORT="7468"
$env:DB_NAME="authprod"
$env:DB_USER="authprod"
$env:DB_PASSWORD="authprod.AI_2025!"
$env:DB_HOST="localhost"
$env:DB_PORT="7001"
$env:DB_SCHEMA="public"
$env:JWT_DEF_SECRET="7f9b2a3c8e6d4f1b9a0c3e7d2f5b8a1c9e3d6f2a4b7c8e0d1f9a2b3c"
$env:JWT_SDK_SECRET="2m1jzDHWPfIGyb3rI4auCGh4KHGh2cy45aHdmWHJjbVVaSU5OeWNXRmhPY1pkNVU"
$env:LOG_LEVEL="info"
$env:SMTP_HOST="smtp.elasticemail.com"
$env:SMTP_PORT="2525"
$env:SMTP_USER="support@authnull.com"
$env:SMTP_PASSWORD="E2AA24DAB22D3996F76B2DCA9F2BFCEDD478"
$env:GIN_MODE="debug"
$env:AUTH_MANAGER_URL="http://localhost:7470"
$env:VAULT_ADDR="http://localhost:8201"
$env:VAULT_TOKEN="hvs.CAESIAfxaMgKBgcRewfLmcBCSYGzZRkeKvwyRuxwafqclQQAGh4KHGh2cy5qeW5QdGF6cm15RnBjZG1mZXJjWGdDbWk"
$env:OOCManagerURL="http://localhost:7467"
$env:ICP_SERVICE_URL="http://localhost:7001"
$env:GOOGLE_CLIENT_SECRET = "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"
$env:BASE_URL = "https://app.authsec.dev"
# Disable SPIRE gRPC client — no SPIRE server in local dev. DB-only mode.
$env:SPIRE_SERVER_ADDR = "disabled"
echo "Environment variables set for Windows environment."
# To run this script, use the command: .\env_vars_windows.ps1
# Ensure to run it in a PowerShell session with appropriate permissions.