// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: proto/tenant_plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TenantPlugin_HealthCheck_FullMethodName           = "/tenantplugin.TenantPlugin/HealthCheck"
	TenantPlugin_AdminRegistered_FullMethodName       = "/tenantplugin.TenantPlugin/AdminRegistered"
	TenantPlugin_GetTenant_FullMethodName             = "/tenantplugin.TenantPlugin/GetTenant"
	TenantPlugin_ListTenants_FullMethodName           = "/tenantplugin.TenantPlugin/ListTenants"
	TenantPlugin_DeleteTenant_FullMethodName          = "/tenantplugin.TenantPlugin/DeleteTenant"
	TenantPlugin_ResolveTenantByDomain_FullMethodName = "/tenantplugin.TenantPlugin/ResolveTenantByDomain"
)

// TenantPluginClient is the client API for TenantPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TenantPlugin is the gRPC service exposed by mt-plugin.
// authsec calls this service for all multi-tenant operations.
type TenantPluginClient interface {
	// HealthCheck is called by authsec every 15s to detect plugin availability.
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// AdminRegistered is called after an admin successfully registers in authsec.
	// mt-plugin handles tenant DB creation, migrations, seeding, Hydra registration.
	AdminRegistered(ctx context.Context, in *AdminRegisteredRequest, opts ...grpc.CallOption) (*AdminRegisteredResponse, error)
	// GetTenant retrieves a tenant record from the master DB.
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error)
	// ListTenants returns all tenant records from the master DB.
	ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error)
	// DeleteTenant drops the tenant DB and removes master DB records.
	DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteTenantResponse, error)
	// ResolveTenantByDomain maps a hostname to a tenant_id via tenant_domains table.
	ResolveTenantByDomain(ctx context.Context, in *ResolveByDomainRequest, opts ...grpc.CallOption) (*ResolveByDomainResponse, error)
}

type tenantPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantPluginClient(cc grpc.ClientConnInterface) TenantPluginClient {
	return &tenantPluginClient{cc}
}

func (c *tenantPluginClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, TenantPlugin_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantPluginClient) AdminRegistered(ctx context.Context, in *AdminRegisteredRequest, opts ...grpc.CallOption) (*AdminRegisteredResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRegisteredResponse)
	err := c.cc.Invoke(ctx, TenantPlugin_AdminRegistered_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantPluginClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*GetTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTenantResponse)
	err := c.cc.Invoke(ctx, TenantPlugin_GetTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantPluginClient) ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantsResponse)
	err := c.cc.Invoke(ctx, TenantPlugin_ListTenants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantPluginClient) DeleteTenant(ctx context.Context, in *DeleteTenantRequest, opts ...grpc.CallOption) (*DeleteTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTenantResponse)
	err := c.cc.Invoke(ctx, TenantPlugin_DeleteTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantPluginClient) ResolveTenantByDomain(ctx context.Context, in *ResolveByDomainRequest, opts ...grpc.CallOption) (*ResolveByDomainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveByDomainResponse)
	err := c.cc.Invoke(ctx, TenantPlugin_ResolveTenantByDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantPluginServer is the server API for TenantPlugin service.
// All implementations must embed UnimplementedTenantPluginServer
// for forward compatibility.
//
// TenantPlugin is the gRPC service exposed by mt-plugin.
// authsec calls this service for all multi-tenant operations.
type TenantPluginServer interface {
	// HealthCheck is called by authsec every 15s to detect plugin availability.
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	// AdminRegistered is called after an admin successfully registers in authsec.
	// mt-plugin handles tenant DB creation, migrations, seeding, Hydra registration.
	AdminRegistered(context.Context, *AdminRegisteredRequest) (*AdminRegisteredResponse, error)
	// GetTenant retrieves a tenant record from the master DB.
	GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error)
	// ListTenants returns all tenant records from the master DB.
	ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error)
	// DeleteTenant drops the tenant DB and removes master DB records.
	DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteTenantResponse, error)
	// ResolveTenantByDomain maps a hostname to a tenant_id via tenant_domains table.
	ResolveTenantByDomain(context.Context, *ResolveByDomainRequest) (*ResolveByDomainResponse, error)
	mustEmbedUnimplementedTenantPluginServer()
}

// UnimplementedTenantPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantPluginServer struct{}

func (UnimplementedTenantPluginServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedTenantPluginServer) AdminRegistered(context.Context, *AdminRegisteredRequest) (*AdminRegisteredResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminRegistered not implemented")
}
func (UnimplementedTenantPluginServer) GetTenant(context.Context, *GetTenantRequest) (*GetTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedTenantPluginServer) ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTenants not implemented")
}
func (UnimplementedTenantPluginServer) DeleteTenant(context.Context, *DeleteTenantRequest) (*DeleteTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTenant not implemented")
}
func (UnimplementedTenantPluginServer) ResolveTenantByDomain(context.Context, *ResolveByDomainRequest) (*ResolveByDomainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveTenantByDomain not implemented")
}
func (UnimplementedTenantPluginServer) mustEmbedUnimplementedTenantPluginServer() {}
func (UnimplementedTenantPluginServer) testEmbeddedByValue()                      {}

// UnsafeTenantPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantPluginServer will
// result in compilation errors.
type UnsafeTenantPluginServer interface {
	mustEmbedUnimplementedTenantPluginServer()
}

func RegisterTenantPluginServer(s grpc.ServiceRegistrar, srv TenantPluginServer) {
	// If the following call panics, it indicates UnimplementedTenantPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TenantPlugin_ServiceDesc, srv)
}

func _TenantPlugin_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantPluginServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantPlugin_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantPluginServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantPlugin_AdminRegistered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRegisteredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantPluginServer).AdminRegistered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantPlugin_AdminRegistered_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantPluginServer).AdminRegistered(ctx, req.(*AdminRegisteredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantPlugin_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantPluginServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantPlugin_GetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantPluginServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantPlugin_ListTenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantPluginServer).ListTenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantPlugin_ListTenants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantPluginServer).ListTenants(ctx, req.(*ListTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantPlugin_DeleteTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantPluginServer).DeleteTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantPlugin_DeleteTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantPluginServer).DeleteTenant(ctx, req.(*DeleteTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantPlugin_ResolveTenantByDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveByDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantPluginServer).ResolveTenantByDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantPlugin_ResolveTenantByDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantPluginServer).ResolveTenantByDomain(ctx, req.(*ResolveByDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantPlugin_ServiceDesc is the grpc.ServiceDesc for TenantPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tenantplugin.TenantPlugin",
	HandlerType: (*TenantPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _TenantPlugin_HealthCheck_Handler,
		},
		{
			MethodName: "AdminRegistered",
			Handler:    _TenantPlugin_AdminRegistered_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _TenantPlugin_GetTenant_Handler,
		},
		{
			MethodName: "ListTenants",
			Handler:    _TenantPlugin_ListTenants_Handler,
		},
		{
			MethodName: "DeleteTenant",
			Handler:    _TenantPlugin_DeleteTenant_Handler,
		},
		{
			MethodName: "ResolveTenantByDomain",
			Handler:    _TenantPlugin_ResolveTenantByDomain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tenant_plugin.proto",
}
