// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/tenant_plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_tenant_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_tenant_plugin_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_tenant_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_tenant_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AdminRegisteredRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DbName        string                 `protobuf:"bytes,3,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"` // e.g. "tenant_550e8400e29b41d4a716446655440000"
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,5,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	ProjectId     string                 `protobuf:"bytes,6,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	TenantDomain  string                 `protobuf:"bytes,8,opt,name=tenant_domain,json=tenantDomain,proto3" json:"tenant_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRegisteredRequest) Reset() {
	*x = AdminRegisteredRequest{}
	mi := &file_proto_tenant_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRegisteredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegisteredRequest) ProtoMessage() {}

func (x *AdminRegisteredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegisteredRequest.ProtoReflect.Descriptor instead.
func (*AdminRegisteredRequest) Descriptor() ([]byte, []int) {
	return file_proto_tenant_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminRegisteredRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AdminRegisteredRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminRegisteredRequest) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *AdminRegisteredRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AdminRegisteredRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *AdminRegisteredRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AdminRegisteredRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminRegisteredRequest) GetTenantDomain() string {
	if x != nil {
		return x.TenantDomain
	}
	return ""
}

type AdminRegisteredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DbName        string                 `protobuf:"bytes,3,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"` // confirmed DB name after creation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRegisteredResponse) Reset() {
	*x = AdminRegisteredResponse{}
	mi := &file_proto_tenant_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRegisteredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRegisteredResponse) ProtoMessage() {}

func (x *AdminRegisteredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRegisteredResponse.ProtoReflect.Descriptor instead.
func (*AdminRegisteredResponse) Descriptor() ([]byte, []int) {
	return file_proto_tenant_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminRegisteredResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminRegisteredResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminRegisteredResponse) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

type GetTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_proto_tenant_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_proto_tenant_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *GetTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type TenantInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	TenantDomain  string                 `protobuf:"bytes,4,opt,name=tenant_domain,json=tenantDomain,proto3" json:"tenant_domain,omitempty"`
	DbName        string                 `protobuf:"bytes,5,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantInfo) Reset() {
	*x = TenantInfo{}
	mi := &file_proto_tenant_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantInfo) ProtoMessage() {}

func (x *TenantInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantInfo.ProtoReflect.Descriptor instead.
func (*TenantInfo) Descriptor() ([]byte, []int) {
	return file_proto_tenant_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *TenantInfo) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TenantInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TenantInfo) GetTenantDomain() string {
	if x != nil {
		return x.TenantDomain
	}
	return ""
}

func (x *TenantInfo) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *TenantInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TenantInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *TenantInfo            `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantResponse) Reset() {
	*x = GetTenantResponse{}
	mi := &file_proto_tenant_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantResponse) ProtoMessage() {}

func (x *GetTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantResponse.ProtoReflect.Descriptor instead.
func (*GetTenantResponse) Descriptor() ([]byte, []int) {
	return file_proto_tenant_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *GetTenantResponse) GetTenant() *TenantInfo {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type ListTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_proto_tenant_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tenant_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ListTenantsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTenantsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*TenantInfo          `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResponse) Reset() {
	*x = ListTenantsResponse{}
	mi := &file_proto_tenant_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResponse) ProtoMessage() {}

func (x *ListTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tenant_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ListTenantsResponse) GetTenants() []*TenantInfo {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *ListTenantsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_proto_tenant_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_proto_tenant_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type DeleteTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantResponse) Reset() {
	*x = DeleteTenantResponse{}
	mi := &file_proto_tenant_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantResponse) ProtoMessage() {}

func (x *DeleteTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantResponse.ProtoReflect.Descriptor instead.
func (*DeleteTenantResponse) Descriptor() ([]byte, []int) {
	return file_proto_tenant_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTenantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteTenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResolveByDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"` // normalized hostname (lowercase, no port)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveByDomainRequest) Reset() {
	*x = ResolveByDomainRequest{}
	mi := &file_proto_tenant_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveByDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveByDomainRequest) ProtoMessage() {}

func (x *ResolveByDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveByDomainRequest.ProtoReflect.Descriptor instead.
func (*ResolveByDomainRequest) Descriptor() ([]byte, []int) {
	return file_proto_tenant_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ResolveByDomainRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type ResolveByDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // empty string if not found
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveByDomainResponse) Reset() {
	*x = ResolveByDomainResponse{}
	mi := &file_proto_tenant_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveByDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveByDomainResponse) ProtoMessage() {}

func (x *ResolveByDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tenant_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveByDomainResponse.ProtoReflect.Descriptor instead.
func (*ResolveByDomainResponse) Descriptor() ([]byte, []int) {
	return file_proto_tenant_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ResolveByDomainResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ResolveByDomainResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_proto_tenant_plugin_proto protoreflect.FileDescriptor

const file_proto_tenant_plugin_proto_rawDesc = "" +
	"\n" +
	"\x19proto/tenant_plugin.proto\x12\ftenantplugin\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xfe\x01\n" +
	"\x16AdminRegisteredRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x17\n" +
	"\adb_name\x18\x03 \x01(\tR\x06dbName\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x05 \x01(\tR\fclientSecret\x12\x1d\n" +
	"\n" +
	"project_id\x18\x06 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12#\n" +
	"\rtenant_domain\x18\b \x01(\tR\ftenantDomain\"f\n" +
	"\x17AdminRegisteredResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\adb_name\x18\x03 \x01(\tR\x06dbName\"/\n" +
	"\x10GetTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\xc8\x01\n" +
	"\n" +
	"TenantInfo\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rtenant_domain\x18\x04 \x01(\tR\ftenantDomain\x12\x17\n" +
	"\adb_name\x18\x05 \x01(\tR\x06dbName\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"E\n" +
	"\x11GetTenantResponse\x120\n" +
	"\x06tenant\x18\x01 \x01(\v2\x18.tenantplugin.TenantInfoR\x06tenant\"C\n" +
	"\x12ListTenantsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\"_\n" +
	"\x13ListTenantsResponse\x122\n" +
	"\atenants\x18\x01 \x03(\v2\x18.tenantplugin.TenantInfoR\atenants\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"2\n" +
	"\x13DeleteTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"J\n" +
	"\x14DeleteTenantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x16ResolveByDomainRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"L\n" +
	"\x17ResolveByDomainResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found2\x97\x04\n" +
	"\fTenantPlugin\x12H\n" +
	"\vHealthCheck\x12\x1b.tenantplugin.HealthRequest\x1a\x1c.tenantplugin.HealthResponse\x12^\n" +
	"\x0fAdminRegistered\x12$.tenantplugin.AdminRegisteredRequest\x1a%.tenantplugin.AdminRegisteredResponse\x12L\n" +
	"\tGetTenant\x12\x1e.tenantplugin.GetTenantRequest\x1a\x1f.tenantplugin.GetTenantResponse\x12R\n" +
	"\vListTenants\x12 .tenantplugin.ListTenantsRequest\x1a!.tenantplugin.ListTenantsResponse\x12U\n" +
	"\fDeleteTenant\x12!.tenantplugin.DeleteTenantRequest\x1a\".tenantplugin.DeleteTenantResponse\x12d\n" +
	"\x15ResolveTenantByDomain\x12$.tenantplugin.ResolveByDomainRequest\x1a%.tenantplugin.ResolveByDomainResponseB'Z%github.com/authsec-ai/mt-plugin/protob\x06proto3"

var (
	file_proto_tenant_plugin_proto_rawDescOnce sync.Once
	file_proto_tenant_plugin_proto_rawDescData []byte
)

func file_proto_tenant_plugin_proto_rawDescGZIP() []byte {
	file_proto_tenant_plugin_proto_rawDescOnce.Do(func() {
		file_proto_tenant_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tenant_plugin_proto_rawDesc), len(file_proto_tenant_plugin_proto_rawDesc)))
	})
	return file_proto_tenant_plugin_proto_rawDescData
}

var file_proto_tenant_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_tenant_plugin_proto_goTypes = []any{
	(*HealthRequest)(nil),           // 0: tenantplugin.HealthRequest
	(*HealthResponse)(nil),          // 1: tenantplugin.HealthResponse
	(*AdminRegisteredRequest)(nil),  // 2: tenantplugin.AdminRegisteredRequest
	(*AdminRegisteredResponse)(nil), // 3: tenantplugin.AdminRegisteredResponse
	(*GetTenantRequest)(nil),        // 4: tenantplugin.GetTenantRequest
	(*TenantInfo)(nil),              // 5: tenantplugin.TenantInfo
	(*GetTenantResponse)(nil),       // 6: tenantplugin.GetTenantResponse
	(*ListTenantsRequest)(nil),      // 7: tenantplugin.ListTenantsRequest
	(*ListTenantsResponse)(nil),     // 8: tenantplugin.ListTenantsResponse
	(*DeleteTenantRequest)(nil),     // 9: tenantplugin.DeleteTenantRequest
	(*DeleteTenantResponse)(nil),    // 10: tenantplugin.DeleteTenantResponse
	(*ResolveByDomainRequest)(nil),  // 11: tenantplugin.ResolveByDomainRequest
	(*ResolveByDomainResponse)(nil), // 12: tenantplugin.ResolveByDomainResponse
}
var file_proto_tenant_plugin_proto_depIdxs = []int32{
	5,  // 0: tenantplugin.GetTenantResponse.tenant:type_name -> tenantplugin.TenantInfo
	5,  // 1: tenantplugin.ListTenantsResponse.tenants:type_name -> tenantplugin.TenantInfo
	0,  // 2: tenantplugin.TenantPlugin.HealthCheck:input_type -> tenantplugin.HealthRequest
	2,  // 3: tenantplugin.TenantPlugin.AdminRegistered:input_type -> tenantplugin.AdminRegisteredRequest
	4,  // 4: tenantplugin.TenantPlugin.GetTenant:input_type -> tenantplugin.GetTenantRequest
	7,  // 5: tenantplugin.TenantPlugin.ListTenants:input_type -> tenantplugin.ListTenantsRequest
	9,  // 6: tenantplugin.TenantPlugin.DeleteTenant:input_type -> tenantplugin.DeleteTenantRequest
	11, // 7: tenantplugin.TenantPlugin.ResolveTenantByDomain:input_type -> tenantplugin.ResolveByDomainRequest
	1,  // 8: tenantplugin.TenantPlugin.HealthCheck:output_type -> tenantplugin.HealthResponse
	3,  // 9: tenantplugin.TenantPlugin.AdminRegistered:output_type -> tenantplugin.AdminRegisteredResponse
	6,  // 10: tenantplugin.TenantPlugin.GetTenant:output_type -> tenantplugin.GetTenantResponse
	8,  // 11: tenantplugin.TenantPlugin.ListTenants:output_type -> tenantplugin.ListTenantsResponse
	10, // 12: tenantplugin.TenantPlugin.DeleteTenant:output_type -> tenantplugin.DeleteTenantResponse
	12, // 13: tenantplugin.TenantPlugin.ResolveTenantByDomain:output_type -> tenantplugin.ResolveByDomainResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_tenant_plugin_proto_init() }
func file_proto_tenant_plugin_proto_init() {
	if File_proto_tenant_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tenant_plugin_proto_rawDesc), len(file_proto_tenant_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tenant_plugin_proto_goTypes,
		DependencyIndexes: file_proto_tenant_plugin_proto_depIdxs,
		MessageInfos:      file_proto_tenant_plugin_proto_msgTypes,
	}.Build()
	File_proto_tenant_plugin_proto = out.File
	file_proto_tenant_plugin_proto_goTypes = nil
	file_proto_tenant_plugin_proto_depIdxs = nil
}
