package services

import (
	"context"
	"crypto/x509"
	"encoding/pem"
	"fmt"
	"net/url"
	"strings"
	"time"

	"github.com/sirupsen/logrus"

	"github.com/authsec-ai/authsec/internal/spire/domain/models"
	"github.com/authsec-ai/authsec/internal/spire/domain/repositories"
	"github.com/authsec-ai/authsec/internal/spire/errors"
	"github.com/authsec-ai/authsec/internal/spire/infrastructure/vault"
)

// WorkloadAttestationService issues workload SVIDs to agents. The agent is
// authenticated by its certificate; the workspace is ctx's.
type WorkloadAttestationService struct {
	workspaceRepo repositories.WorkspaceRepository
	entryRepo     repositories.WorkloadEntryRepository
	vaultClient   *vault.Client
	logger        *logrus.Entry
}

// NewWorkloadAttestationService creates the workload attestation service.
func NewWorkloadAttestationService(
	workspaceRepo repositories.WorkspaceRepository,
	entryRepo repositories.WorkloadEntryRepository,
	vaultClient *vault.Client,
	logger *logrus.Entry,
) *WorkloadAttestationService {
	return &WorkloadAttestationService{
		workspaceRepo: workspaceRepo,
		entryRepo:     entryRepo,
		vaultClient:   vaultClient,
		logger:        logger,
	}
}

// AttestWorkloadRequest is a workload attestation by an agent.
type AttestWorkloadRequest struct {
	// AgentID is the authenticated agent's SPIFFE ID (from its certificate).
	AgentID   string            `json:"agent_id"`
	Selectors map[string]string `json:"selectors"` // workload selectors collected by the agent
	CSR       string            `json:"csr"`       // PEM CSR generated by the workload
}

// AttestWorkloadResponse represents the SVID issued to the workload
type AttestWorkloadResponse struct {
	SpiffeID    string    `json:"spiffe_id"`
	Certificate string    `json:"certificate"`
	TrustBundle string    `json:"trust_bundle"`
	ExpiresAt   time.Time `json:"expires_at"`
	TTL         int       `json:"ttl"`
}

// AttestWorkload matches the selectors to an entry of ctx's workspace that
// the agent serves and issues its SVID.
func (s *WorkloadAttestationService) AttestWorkload(ctx context.Context, req *AttestWorkloadRequest) (*AttestWorkloadResponse, error) {
	workspaceID, err := workspaceFromContext(ctx)
	if err != nil {
		return nil, err
	}
	tenant, err := s.workspaceRepo.GetByID(ctx, workspaceID)
	if err != nil {
		return nil, errors.NewNotFoundError("Workspace not found", err)
	}

	entries, err := s.entryRepo.FindMatchingEntries(ctx, req.Selectors)
	if err != nil {
		return nil, errors.NewInternalError("Failed to find matching workload entries", err)
	}
	// Prefer the agent's own entries, then the most specific one. An entry
	// assigned to another agent is never a candidate.
	var entry *models.WorkloadEntry
	best := -1
	for _, e := range entries {
		if e.ParentID != "" && e.ParentID != req.AgentID {
			continue
		}
		score := len(e.Selectors)
		if e.ParentID == req.AgentID {
			score += 1000
		}
		if score > best {
			best, entry = score, e
		}
	}
	if entry == nil {
		return nil, errors.NewNotFoundError("No workload entry of this agent matches the selectors", nil)
	}

	if req.CSR == "" {
		return nil, errors.NewBadRequestError("CSR is required: the workload must generate its own keypair", nil)
	}
	csrBlock, _ := pem.Decode([]byte(req.CSR))
	if csrBlock == nil {
		return nil, errors.NewBadRequestError("Invalid CSR format", nil)
	}
	csr, err := x509.ParseCertificateRequest(csrBlock.Bytes)
	if err != nil {
		return nil, errors.NewBadRequestError("Failed to parse CSR", err)
	}
	if err := csr.CheckSignature(); err != nil {
		return nil, errors.NewBadRequestError("Invalid CSR signature", err)
	}

	spiffeURI, err := url.Parse(entry.SpiffeID)
	if err != nil {
		return nil, errors.NewInternalError("Invalid SPIFFE ID on entry", err)
	}
	parts := strings.Split(spiffeURI.Path, "/")
	cn := parts[len(parts)-1]
	ttl := 3600
	if entry.TTL != nil {
		ttl = *entry.TTL
	}

	if !s.vaultClient.Available() {
		return nil, vault.ErrUnavailable
	}
	if tenant.VaultMount == "" {
		return nil, errors.NewServiceUnavailableError("Workspace PKI is not provisioned", nil)
	}
	certResp, err := s.vaultClient.IssueCertificate(ctx, tenant.VaultMount, "workload", &vault.CertificateRequest{
		CSR:        req.CSR,
		CommonName: cn,
		TTL:        fmt.Sprintf("%ds", ttl),
		URISANs:    []string{entry.SpiffeID},
	})
	if err != nil {
		return nil, errors.NewInternalError("Failed to issue certificate", err)
	}
	trustBundle, err := s.vaultClient.GetCABundle(ctx, tenant.VaultMount)
	if err != nil {
		return nil, errors.NewInternalError("Failed to get CA bundle", err)
	}

	expires := time.Now().Add(time.Duration(ttl) * time.Second)
	if err := s.entryRepo.RecordSVID(ctx, &models.WorkloadSVID{
		EntryID:       entry.ID,
		AgentSpiffeID: req.AgentID,
		SpiffeID:      entry.SpiffeID,
		SerialNumber:  certResp.SerialNumber,
		TTL:           ttl,
		ExpiresAt:     expires,
	}); err != nil {
		s.logger.WithField("spiffe_id", entry.SpiffeID).WithError(err).Warn("Failed to record workload SVID")
	}

	return &AttestWorkloadResponse{
		SpiffeID:    entry.SpiffeID,
		Certificate: certResp.Certificate,
		TrustBundle: trustBundle,
		ExpiresAt:   expires,
		TTL:         ttl,
	}, nil
}

// RevokeWorkloadSVID revokes an SVID the authenticated agent obtained in
// ctx's workspace. Any other serial (another agent's, another workspace's,
// unknown) is not found.
func (s *WorkloadAttestationService) RevokeWorkloadSVID(ctx context.Context, agentSpiffeID, serialNumber string) error {
	workspaceID, err := workspaceFromContext(ctx)
	if err != nil {
		return err
	}
	svid, err := s.entryRepo.GetSVIDBySerial(ctx, serialNumber)
	if err != nil {
		return err
	}
	if svid.AgentSpiffeID != agentSpiffeID {
		return errors.NewNotFoundError("Workload SVID not found", nil)
	}
	tenant, err := s.workspaceRepo.GetByID(ctx, workspaceID)
	if err != nil {
		return errors.NewNotFoundError("Workspace not found", err)
	}
	if !s.vaultClient.Available() {
		return vault.ErrUnavailable
	}
	if err := s.vaultClient.RevokeCertificate(ctx, tenant.VaultMount, serialNumber); err != nil {
		return errors.NewInternalError("Failed to revoke certificate", err)
	}
	return s.entryRepo.MarkSVIDRevoked(ctx, serialNumber)
}
