package services

import (
	"testing"

	"github.com/authsec-ai/authsec/models"
	"github.com/google/uuid"
	"github.com/stretchr/testify/require"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

// newRSServiceTestDB builds an in-memory sqlite DB with just enough of the
// schema to exercise ResourceServerService.Create. ID columns use sqlite's
// randomblob() so the rows generated by the service get a value without the
// model needing to call uuid.New() itself.
func newRSServiceTestDB(t *testing.T) *gorm.DB {
	t.Helper()

	db, err := gorm.Open(sqlite.Open("file:"+t.Name()+"?mode=memory&cache=shared"), &gorm.Config{})
	require.NoError(t, err)

	stmts := []string{
		`CREATE TABLE resource_servers (
			id                          TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
			workspace_id                TEXT NOT NULL,
			workspace_id                   TEXT,
			application_type            TEXT NOT NULL DEFAULT 'mcp_server',
			legacy_client_id            TEXT,
			name                        TEXT NOT NULL,
			public_base_url             TEXT NOT NULL,
			protected_base_path         TEXT NOT NULL,
			resource_uri                TEXT NOT NULL,
			scopes_supported            TEXT,
			registration_modes          TEXT,
			introspection_secret        TEXT,
			introspection_secret_hash   TEXT,
			active                      NUMERIC,
			state                       TEXT NOT NULL,
			setup_completed_at          DATETIME,
			setup_completed_by          TEXT,
			status                      TEXT NOT NULL,
			scan_generation             INTEGER NOT NULL DEFAULT 0,
			last_successful_generation  INTEGER NOT NULL DEFAULT 0,
			scan_in_progress            NUMERIC NOT NULL DEFAULT 0,
			last_scan_status            TEXT,
			last_scan_error             TEXT,
			last_scan_started_at        DATETIME,
			last_scan_completed_at      DATETIME,
			last_validated_at           DATETIME,
			last_validation_status      TEXT,
			last_validation_error       TEXT,
			created_at                  DATETIME,
			updated_at                  DATETIME,
			deleted_at                  DATETIME
		)`,
		`CREATE TABLE roles (
			id                TEXT PRIMARY KEY,
			workspace_id      TEXT,
			workspace_id         TEXT,
			name              TEXT NOT NULL,
			description       TEXT,
			is_system         NUMERIC NOT NULL DEFAULT 0,
			created_at        DATETIME,
			updated_at        DATETIME,
			deleted_at        DATETIME
		)`,
		`CREATE TABLE resource_server_access_policies (
			id                  TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
			workspace_id        TEXT NOT NULL,
			workspace_id           TEXT,
			resource_server_id  TEXT NOT NULL,
			enabled             NUMERIC NOT NULL DEFAULT 0,
			default_role_id     TEXT,
			assignment_trigger  TEXT NOT NULL DEFAULT 'first_successful_login',
			assignment_source   TEXT NOT NULL DEFAULT 'default_policy',
			created_at          DATETIME,
			updated_at          DATETIME
		)`,
		`CREATE TABLE oauth_scopes (
			id                  TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
			workspace_id        TEXT NOT NULL,
			workspace_id           TEXT,
			resource_server_id  TEXT,
			scope_string        TEXT NOT NULL,
			display_name        TEXT NOT NULL,
			description         TEXT,
			icon                TEXT,
			risk_level          TEXT NOT NULL DEFAULT 'low',
			parent_scope_id     TEXT,
			is_auto_discovered  NUMERIC NOT NULL DEFAULT 0,
			source              TEXT NOT NULL DEFAULT 'discovered',
			created_at          DATETIME,
			updated_at          DATETIME,
			UNIQUE (workspace_id, resource_server_id, scope_string)
		)`,
	}
	for _, s := range stmts {
		require.NoError(t, db.Exec(s).Error)
	}
	return db
}

func ptrString(s string) *string { return &s }
func ptrBool(b bool) *bool       { return &b }

func TestCreateResourceServer_DefaultAccessClosed(t *testing.T) {
	t.Parallel()

	db := newRSServiceTestDB(t)
	svc := NewResourceServerService(db)

	rs, _, err := svc.Create(CreateResourceServerRequest{
		WorkspaceID:   uuid.New(),
		Name:          "Closed RS",
		PublicBaseURL: "https://example.com",
	}, "https://auth.example.com")
	require.NoError(t, err)
	require.NotNil(t, rs)

	var policy models.ResourceServerAccessPolicy
	require.NoError(t, db.Where("resource_server_id = ?", rs.ID).First(&policy).Error)
	require.False(t, policy.Enabled,
		"default access policy must be closed (Enabled=false) unless DefaultAccessEnabled=true")
}

func TestCreateResourceServer_DefaultAccessEnabledExplicit(t *testing.T) {
	t.Parallel()

	db := newRSServiceTestDB(t)
	svc := NewResourceServerService(db)

	rs, _, err := svc.Create(CreateResourceServerRequest{
		WorkspaceID:          uuid.New(),
		Name:                 "Open RS",
		PublicBaseURL:        "https://example.com",
		DefaultAccessEnabled: ptrBool(true),
	}, "https://auth.example.com")
	require.NoError(t, err)
	require.NotNil(t, rs)

	var policy models.ResourceServerAccessPolicy
	require.NoError(t, db.Where("resource_server_id = ?", rs.ID).First(&policy).Error)
	require.True(t, policy.Enabled,
		"caller asked for DefaultAccessEnabled=true; policy must reflect that")
}

func TestCreateResourceServer_SeedsPresetScopes(t *testing.T) {
	t.Parallel()

	db := newRSServiceTestDB(t)
	svc := NewResourceServerService(db)

	rs, _, err := svc.Create(CreateResourceServerRequest{
		WorkspaceID:   uuid.New(),
		Name:          "GitHub MCP",
		PublicBaseURL: "https://github.example.com",
		ScopePresetID: ptrString("read_write"),
	}, "https://auth.example.com")
	require.NoError(t, err)
	require.NotNil(t, rs)

	var scopes []models.OAuthScope
	require.NoError(t, db.Where("resource_server_id = ?", rs.ID).Order("scope_string").Find(&scopes).Error)
	require.Len(t, scopes, 4, "read_write preset must seed the canonical read/write and tools scopes")

	expectedStrings := []string{"github_mcp:read", "github_mcp:tools:read", "github_mcp:tools:write", "github_mcp:write"}
	for i, sc := range scopes {
		require.Equal(t, expectedStrings[i], sc.ScopeString)
		require.Equal(t, "preset", sc.Source, "preset-seeded scopes must carry source='preset'")
		require.False(t, sc.IsAutoDiscovered, "preset scopes are not auto-discovered")
	}
}

func TestCreateResourceServer_BlankPresetSeedsNothing(t *testing.T) {
	t.Parallel()

	db := newRSServiceTestDB(t)
	svc := NewResourceServerService(db)

	rs, _, err := svc.Create(CreateResourceServerRequest{
		WorkspaceID:   uuid.New(),
		Name:          "Blank RS",
		PublicBaseURL: "https://example.com",
		ScopePresetID: ptrString("blank"),
	}, "https://auth.example.com")
	require.NoError(t, err)

	var count int64
	db.Model(&models.OAuthScope{}).Where("resource_server_id = ?", rs.ID).Count(&count)
	require.Zero(t, count, "blank preset must not seed any scopes")
}

func TestCreateResourceServer_UnknownPresetIgnored(t *testing.T) {
	t.Parallel()

	db := newRSServiceTestDB(t)
	svc := NewResourceServerService(db)

	rs, _, err := svc.Create(CreateResourceServerRequest{
		WorkspaceID:   uuid.New(),
		Name:          "Mystery RS",
		PublicBaseURL: "https://example.com",
		ScopePresetID: ptrString("does_not_exist"),
	}, "https://auth.example.com")
	require.NoError(t, err, "unknown preset IDs must be ignored, not fatal")

	var count int64
	db.Model(&models.OAuthScope{}).Where("resource_server_id = ?", rs.ID).Count(&count)
	require.Zero(t, count)
}
